language: swift
osx_image: xcode10.1
xcode_workspace: ResourceKit.xcworkspace # Path to your xcodeproj folder.
xcode_scheme: ResourceKit
xcode_destination: platform=iOS Simulator,OS=12.1.4,name=iPhone XS Max
#before_install:
#    - pod install
after_success:
    - gem install jazzy
    - make docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: master

